services:
  mesoftx-frontend:
    build:
      context: ../..
      dockerfile: deployment/frontend/Dockerfile
    container_name: mesoftx-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    networks:
      - mesoftx-network

networks:
  mesoftx-network:
    external: true
    name: mesoftx-network
